version: "3"

services:
  route-checker:
    container_name: route-checker
    image: docker.sprun.ir/route-checker
    build:
      context: ./
      dockerfile: ./infra/docker/route-checker/Dockerfile
    restart: unless-stopped
    ports:
      - "2348:2344"
    volumes:
      - ./assets:/app/assets:ro
      - ./infra/logs:/app/logs:rw