name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:latest
        options: --privileged
    steps:
      - uses: actions/checkout@v4 # use this is an action to check the repo codes
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin docker.yourdomain.com
      - name: Build and Push
        run: |
          docker compose -f "docker-compose.yml" build
          docker compose -f "docker-compose.yml" push
  pull-on-server:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master # use this is an action to login into the ssh
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 3360
          script: | # for none root user the default current directory is /home
            cd /home/user01/apps/geo-checker
            docker compose -f "docker-compose.yml" pull
            docker compose -f "docker-compose.yml" up -d 
